#ifndef Enum_h__
#define Enum_h__

enum RESOURCEID { RESOURCE_STATIC, RESOURCE_LOGO, RESOURCE_STAGE, RESOURCE_END };
enum LOADINGID  { LOADING_STAGE, LOADING_BOSS, LOADING_END };

enum WEAPONTYPE { WEAPONTYPE_DEFAULT, WEAPONTYPE_STAFF, WEAPONTYPE_CROSSBOW, WEAPONTYPE_GUN, WEAPONTYPE_END };
enum WEAPONID { WEAPONID_01, WEAPONID_02, WEAPONID_END };
enum AMMOTYPE { AMMO_REVOLVER, AMMO_SPELL, AMMO_ARROW, AMMO_MINIGUN, AMMO_ROCKETLAUNCHER, AMMO_END };
enum EFFECT { EFFECT_DAGGER, EFFECT_ARROW, EFFECT_SPELLSPHERE, EFFECT_EXPLOSION, EFFECT_SHOCK, EFFECT_BULLET, EFFECT_BLOOD, EFFECT_END };
enum LOGO { START_GAME, EXIT_GAME };
namespace Animation
{
	/* Weapon */
	enum DAGGER { DAGGER_IDLE, DAGGER_STAB, DAGGER_THROW, DAGGER_END };
	enum STAFF { STAFF_IDLE, STAFF_FIRE, STAFF_CHARGE, STAFF_CHARGELOOP, STAFF_CHARGERELEASE, STAFF_END };
	enum REVOLVER { REVOLVER_IDLE, REVOLVER_SHOT, REVOLVER_END };
	enum CROSSBOW { CROSSBOW_IDLE, CROSSBOW_FIRE, CROSSBOW_RELOAD, CROSSBOW_END };
	enum CROSSBOW3 { CROSSBOW3_ARROWLEFT1, CROSSBOW3_ARROWLEFT2, CROSSBOW3_ARROWLEFT3, CROSSBOW3_RELOAD, CROSSBOW3_END };
	enum COLDSTAFF { COLDSTAFF_IDLE, COLDSTAFF_ATTACK, COLDSTAFF_END };
	enum MINIGUN { MINIGUN_ROTATE, MINIGUN_BELT, MINIGUN_FIRE, MINIGUN_TURRETMODE, MINIGUN_TURRETMODEIDLE, MINIGUN_TURRETMODEFIRE, MINIGUN_END };
	enum ROCKETLAUNCHER { ROCKETLAUNCHER_IDLE, ROCKETLAUNCHER_FIRE, ROCKETLAUNCHER_END };

	/* Monster*/
	enum MONSTER { MON_IDLE, MON_BACK, MON_ATTACK, MON_SHOOT, MON_HIT, MON_DEATH, MON_END };

}


#endif // Enum_h__
