#ifndef Enum_h__
#define Enum_h__

enum RESOURCEID { RESOURCE_STATIC, RESOURCE_LOGO, RESOURCE_STAGE, RESOURCE_END };
enum LOADINGID  { LOADING_STAGE, LOADING_BOSS, LOADING_END };


enum WEAPONTYPE { WEAPONTYPE_NEAR, WEAPONTYPE_GUN, WEAPONTYPE_STAFF, WEAPONTYPE_CROSSBOW, WEAPONTYPE_END };
enum WEAPONID { WEAPONID_01, WEAPONID_02, WEAPONID_END };

namespace Animation
{
	enum DAGGER { DAGGER_IDLE, DAGGER_STAB, DAGGER_THROW, DAGGER_END };
	enum BAT{BAT_IDLE,BAT_BACK,BAT_ATTACK,BAT_SHOOT,BAT_HIT,BAT_DEATH,BAT_END};
}


#endif // Enum_h__
